tasks:
  # read dataset
  - source: french_exercises/read_data.py
    name: read-data
    product:
      nb: output/read_data.html
      data: output/df_petitprince.csv

  # model training
  - source: french_exercises/model.py
    name: model
    product:
      nb: output/model.html

  # decode dataset
  - source: french_exercises/decode_data.py
    name: decode-data
    product:
      nb: output/decode_data.html
      data: output/df_QA_petitprince.csv
