name: ci-cd

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - .github/workflows/ci-cd.yaml
      - french_exercises/**
      - tests/**
  release:
    types:
      - published

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[quality]"

      - name: check-quality
        run: |
          ruff french_exercises tests
          black french_exercises tests

  run-tests:
    needs: check-quality

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"
          pip install ".[dev]"
          pip install -e .

      - name: run-tests
        run: pytest -v --doctest-modules tests

  deploy-docs:
    needs: run-tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      - name: deploy-to-gh-pages
        run: mkdocs gh-deploy --force
